### ISSUE TITLE
Move repo to /ckan/ckanext-issues

### ISSUE THREAD

**Issue by davidread** [ckan/ckanext-issues#55]
datagovuk is maintaining this repo over on their fork, and rather than them hassling okfn as they have several times in the past to merge their changes, I'm wondering if now okfn have finished their paid-for work they should pass the repo to the CKAN community to continue development in a new home at github.com/ckan? The problem is that while it lives in okfn that will be the default home everyone where everyone will look. There are two other forks off okfn's potentially dead mainline, rather than the live datagovuk one. Users are raising issues and pull-requests that are ignored on okfn's one. I think it would be better to move this repo to http://github.com/ckan/ckanext-issues and datagovuk take over official responsibility for it.

Thoughts @rgrp?

**Comment by deniszgonjanin** [comment]
:+1:

**Comment by rgrp** [comment]
@davidread this seems great generally as an approach at this point.

And sorry if you have not been able to get things merged - and being able to converge the DGU fork and this would be great. I suggest you take over as lead maintainer.

**Comment by davidread** [comment]
Super, thanks
