### ISSUE TITLE
TemplateNotFound

### ISSUE THREAD

**Issue by m-sinclair** [ckan/ckanext-issues#58]
I'm getting this error on CKAN 2.41 -  TemplateNotFound: Template issues/dataset.html cannot be found

**Comment by m-sinclair** [comment]
So this worked by doing python develop but not via pip install

**Comment by davidread** [comment]
Neve use 'pip install' with ckan, always use 'pip install -e'. We're too lazy to add all the files to the manifest and -e works just fine afaict.

**Comment by davidread** [comment]
Thanks for the tip, I've fixed the readme.

**Comment by m-sinclair** [comment]
Thanks
ᐧ
