### ISSUE TITLE
ckan route misconfiguration

### ISSUE THREAD

**Issue by datalocale** [ckan/ckanext-issues#63]
When installing and activating the ckanext-issues plugin on a ckan 2.5.2 site there seems to be a configuration issue.
All form submission (add issue, comment on issue) led to a server error 500

For exemple : 
https://www.datalocale.fr/dataset/liste-des-activites-de-pratique-equestre-en-aquitaine/
https://www.datalocale.fr/dataset/liste-des-activites-de-pratique-equestre-en-aquitaine/issues/new 

Is this an identified issue ? :)

**Comment by davidread** [comment]
What exception do you get?

**Comment by datalocale** [comment]
On issue creation I see this message in paster.log

Mailing to datalocale@gironde.fr (and 0 others):
On Ressourcerie datalocale a user has raised an issue with one of the datasets from organization 'Département de la Gironde', for which you are an Administrateur.' for which you are an .

The dataset is: Liste des contacts des structures pour les jeunes gironde
The issue is:

> [Ressourcerie datalocale Issue] Liste des contacts des structures pour les
> jeunes gironde
> sdfgsdfg

Please correct the problem or add an initial comment about the issue at: https://datalocale.fr/dataset/liste-des-contacts-des-structures-pour-les-jeunes-gironde/issues/1. Once the issue has been resolved, click 'Close issue'.

Thank you,

The Ressourcerie datalocale team

--

Issue: https://datalocale.fr/dataset/liste-des-contacts-des-structures-pour-les-jeunes-gironde/issues/1
Dataset: https://datalocale.fr/dataset/liste-des-contacts-des-structures-pour-les-jeunes-gironde
User: datalocaleadmin
Error - <class 'socket.gaierror'>: [Errno -2] Name or service not known
2016-07-22 13:55:32,172 INFO  [ckan.lib.base]  /dataset/liste-des-contacts-des-structures-pour-les-jeunes-gironde/issues/new render time 0.091 seconds

On trying to comment on existing issue

Error - <type 'exceptions.TypeError'>: _get_issue_vars() takes exactly 4 arguments (3 given)
2016-07-22 13:57:42,132 INFO  [ckan.lib.base]  /dataset/fcee1c0f-3ac1-4a4d-9657-75aece9c3476/issues/1/comments render time 0.096 seconds

on issue assignment

Error - <class 'socket.gaierror'>: [Errno -2] Name or service not known
2016-07-22 13:59:18,381 INFO  [ckan.lib.base]  /dataset/fcee1c0f-3ac1-4a4d-9657-75aece9c3476/issues/1/assign render time 0.089 seconds

Thanks

**Comment by davidread** [comment]
The error '_get_issue_vars' is fixed by https://github.com/ckan/ckanext-issues/pull/64

The error '[Errno -2] Name or service not known' is probably due to a problem with your smtp settings. Check your config values for: smtp.server, smtp.starttls, smtp.user and smtp.password

**Comment by datalocale** [comment]
Thanks,
I have applied this commit but the result is the same. The issue is declared, the comment can be returnes, the issue can be assigned but each time I get an 500 Server Error "An internal server error occurred" on submitting.
No exception can be seen on paster.log. Are there any other places to look for log details ?

ex : https://www.datalocale.fr/dataset/c8da2909-2aa9-4f38-9475-7b7383af7e72/issues

**Comment by davidread** [comment]
In the log file you previously detailed, have those errors gone or not?

Maybe ask on ckan-dev or stackoverflow for help configuring your logging if unsure.

**Comment by datalocale** [comment]
Yes the errors have gone. I will try the debug mode on my dev instance.
Thanks
